### ISSUE TITLE
Cannot build Judokit-iOS

### ISSUE THREAD

**Issue by OJDee** [Judopay/DeviceDNA-iOS#14]
Please see related issue:
https://github.com/Judopay/JudoKit-iOS/issues/243

Currently unable to push production builds for our customers

**Comment by stefan-tudor** [comment]
The problem described in https://github.com/Judopay/JudoKit-iOS/issues/243 is a `JudoKit-iOS` specific issue, not a `DeviceDNA-iOS` issue.

The code you're referring to in the original issue [no longer exists](https://github.com/Judopay/JudoKit-iOS/blob/25da610eec9f994cec13eb511c4c45549cecae6f/Source/Models/TransactionEnricher/JPRequestEnricher.m#L58) in the `master` branch of `JudoKit-iOS`, I suspect you have a cached version of `JudoKit-iOS` pulled before this: https://github.com/Judopay/JudoKit-iOS/pull/242 was merged.

**Comment by stefan-tudor** [comment]
https://github.com/Judopay/JudoKit-iOS/issues/243#issuecomment-2085547401
